catalog:
  "@types/node": ^25.6.0
  jest: ^30.3.0

logFilters:
  - code: YN0060
    level: discard
    pattern: "@types/react is listed by your project with version * which doesn't satisfy what @material-ui/*"
  - code: YN0060
    level: discard
    pattern: react is listed by your project with version * which doesn't satisfy what @material-ui/*
  - code: YN0060
    level: discard
    pattern: react-dom is listed by your project with version * which doesn't satisfy what @material-ui/*
  - code: YN0086
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: 0cfdc882d3c1395592aa6d4690958e70ebbc3a8ee1d888d523dc9e3c74796de26f744c37df66a69212280634f422a88074ba625dce0f7886fbdf2a904a0c38a2
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/releases/1.51.2/yarn-plugin"
