app:
  baseUrl: https://kv-ros-backstage-245zlcbrnq-lz.a.run.app
  backendUrl: https://kv-ros-backend-245zlcbrnq-lz.a.run.app

backend:
  baseUrl: https://kv-ros-backstage-245zlcbrnq-lz.a.run.app
  listen:
    port: 7007
  csp:
    connect-src: [ "'self'", 'http:', 'https:' ]
  cors:
    origin: [ 'https://kv-ros-backstage-245zlcbrnq-lz.a.run.app/' ]
    methods: [ GET, HEAD, PATCH, POST, PUT, DELETE ]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'



techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

integrations:
  github:
    - host: github.com
      apps:
        - appId: ${GITHUB_APP_ID}
          privateKey: ${GITHUB_APP_PK}
          webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
          clientId: ${GITHUB_APP_CLIENT_ID}
          clientSecret: ${GITHUB_APP_CLIENT_SECRET}

auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        additionalScopes:
          - Mail.Send

    github:
      development:
        clientId: ${GITHUB_APP_CLIENT_ID}
        clientSecret: ${GITHUB_APP_CLIENT_SECRET}
        callbackUrl: https://kv-ros-backstage-245zlcbrnq-lz.a.run.app/api/auth/github/handler/frame

catalog:
  rules:
    - allow: [ Component, Group, User, Resource, Location, Template, System ]
  locations: [ ]
  providers:
    github:
      spire-test:
        organization: 'spire-test'
        catalogPath: '.security/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '^kv-ros-.*$'
        schedule:
          frequency: { minutes: 1440 }
          timeout: { minutes: 3 }

    githubOrg:
      - spire-test-org:
        organization: 'spire-test'
        catalogPath: '.security/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '*'
        schedule:
          frequency: { minutes: 1440 }
          timeout: { minutes: 3 }

    microsoftGraphOrg:
      development:
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}

        user:
          filter: accountEnabled eq true and userType eq 'member'
        group:
          filter: >
            securityEnabled eq false
            and mailEnabled eq true
            and groupTypes/any(c:c+eq+'Unified')
        schedule:
          frequency: PT1H
          timeout: PT50M
