app:
  baseUrl: https://risc-457384642040.europe-north1.run.app

backend:
  baseUrl: https://risc-457384642040.europe-north1.run.app
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ['https://risc-457384642040.europe-north1.run.app/']
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  auth:
    keys:
      - secret: ${BACKEND_AUTH_KEY}

proxy:
  endpoints:
    '/risc-proxy':
      target: https://risc-backend-457384642040.europe-north1.run.app
      allowedHeaders:
        ['Authorization', 'GCP-Access-Token', 'GitHub-Access-Token']

integrations:
  github:
    - host: github.com
      apps:
        - appId: ${GITHUB_APP_ID}
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          privateKey: ${GITHUB_PRIVATE_KEY}
          webhookSecret: ${GITHUB_WEBHOOK_SECRET}

auth:
  environment: production
  providers:
    microsoft:
      production:
        tenantId: ${ENTRA_ID_TENANT_ID}
        clientId: ${ENTRA_ID_CLIENT_ID}
        clientSecret: ${ENTRA_ID_CLIENT_SECRET}
    google:
      production:
        clientId: ${GOOGLE_CLIENT_ID}
        clientSecret: ${GOOGLE_CLIENT_SECRET}
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}

catalog:
  providers:
    microsoftGraphOrg:
      default:
        queryMode: 'advanced'
        user:
          filter: accountEnabled eq true and userType eq 'member'
          select:
            [
              'accountEnabled',
              'displayName',
              'givenName',
              'id',
              'mail',
              'mailNickname',
              'userPrincipalName',
              'surname',
              'companyName',
              'userType',
            ]
        group:
          filter: >
            startswith(displayName, 'AAD - TF')
        schedule:
          frequency: PT1H
          timeout: PT50M
        tenantId: ${ENTRA_ID_TENANT_ID}
        clientId: ${ENTRA_ID_CLIENT_ID}
        clientSecret: ${ENTRA_ID_CLIENT_SECRET}
