app:
  baseUrl: http://localhost:7007
  backendUrl: https://kv-ros-backend-245zlcbrnq-lz.a.run.app

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: [ "'self'", 'http:', 'https:' ]
  cors:
    origin: [ 'https://kv-ros-backstage-245zlcbrnq-lz.a.run.app/' ]
    methods: [ GET, HEAD, PATCH, POST, PUT, DELETE ]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

catalog:
  locations: [ ]
  providers:
    github:
      providerId:
        organization: 'bekk'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '^kv-ros-.*$'
        schedule:
          frequency: { minutes: 1440 }
          timeout: { minutes: 3 }
