app:
  baseUrl: https://kv-ros-backstage-245zlcbrnq-lz.a.run.app
  backendUrl: https://kv-ros-backend-245zlcbrnq-lz.a.run.app

backend:
  baseUrl: https://kv-ros-backstage-245zlcbrnq-lz.a.run.app
  listen:
    port: 7007
  csp:
    connect-src: [ "'self'", 'http:', 'https:' ]
  cors:
    origin: [ 'https://kv-ros-backstage-245zlcbrnq-lz.a.run.app/' ]
    methods: [ GET, HEAD, PATCH, POST, PUT, DELETE ]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'


techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.


catalog:
  rules:
    - allow: [ Component, Group, User, Resource, Location, Template, System ]
  locations: [ ]
  providers:
    github:
      providerId:
        organization: 'bekk'
        catalogPath: '.security/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '^kv-ros-.*$'
        schedule:
          frequency: { minutes: 1440 }
          timeout: { minutes: 3 }

    microsoftGraphOrg:
      default:
        tenantId: ${AZURE_TENANT_ID}
        user:
          filter: accountEnabled eq true and userType eq 'member'
        group:
          filter: >
            securityEnabled eq false
            and mailEnabled eq true
            and groupTypes/any(c:c+eq+'Unified')
        schedule:
          frequency: PT1H
          timeout: PT50M
