# nonk8s
apiVersion: 'backstage.io/v1alpha1'
kind: 'Component'
metadata:
  name: 'backstage-plugin-risk-scorecard-frontend'
  tags:
    - 'internal'
spec:
  type: 'website'
  lifecycle: 'production'
  owner: 'skvis'
  system: 'ros-as-code'
