# nonk8s
apiVersion: 'backstage.io/v1alpha1'
kind: 'Component'
metadata:
  name: 'backstage-plugin-risk-scorecard-frontend'
  tags:
    - 'internal'
spec:
  type: 'website'
  lifecycle: 'production'
  owner: 'skvis'
  system: 'ros-as-code'
---
apiVersion: 'backstage.io/v1alpha1'
kind: 'Group'
metadata:
  name: 'security_champion_backstage-plugin-risk-scorecard-frontend'
  title: 'Security Champion backstage-plugin-risk-scorecard-frontend'
spec:
  type: 'security_champion'
  parent: 'eiendom_security_champions'
  members:
    - 'jorn-ola-birkeland'
  children:
    - 'resource:backstage-plugin-risk-scorecard-frontend'
---
apiVersion: 'backstage.io/v1alpha1'
kind: 'Resource'
metadata:
  name: 'backstage-plugin-risk-scorecard-frontend'
  links:
    - url: 'https://github.com/kartverket/backstage-plugin-risk-scorecard-frontend'
      title: 'backstage-plugin-risk-scorecard-frontend på GitHub'
spec:
  type: 'repo'
  owner: 'security_champion_backstage-plugin-risk-scorecard-frontend'
  dependencyOf:
    - 'component:backstage-plugin-risk-scorecard-frontend'
