apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-risk-scorecard-frontend
  tags:
    - internal
spec:
  type: website
  lifecycle: production
  owner: skvis
  system: system:default/ros-as-code
  consumesApis:
    - api:default/backstage-plugin-risk-scorecard-backend-api
  dependsOn:
    - component:default/backstage-plugin-risk-scorecard-backend
