apiVersion: backstage.io/v1alpha1
kind: Component
description: |
  An example of a Backstage application.
metadata:
  name: kv-ros-backstage
  annotations:
     github.com/project-slug: bekk/kv-ros-backstage
spec:
  type: website
  owner: rosene
  lifecycle: experimental
