apiVersion: backstage.io/v1alpha1
kind: Component
description: |
  An example of a Backstage application.
metadata:
  name: kv-ros-backstage
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
