steps:
  # Create and use a buildx builder
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'mybuilder', '--use']

  # Build with buildx
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'buildx'
      - 'build'
      - '--load'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backstage:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backstage:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/backstage:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/backstage:latest'

# Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'risc'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backstage:$SHORT_SHA'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'

images:
  - 'gcr.io/$PROJECT_ID/backstage:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/backstage:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Use a larger machine for faster builds
