export const FRONTEND_URLS = {
  index: '/',
  catalog: '/catalog',
  catalog_entity: '/catalog/:namespace/:kind/:name',
  docs: '/docs',
  create: '/create',
  api_docs: '/api-docs',
  tech_docs_reader_page: '/docs/:namespace/:kind/:name/*',
  tech_radar: '/tech-radar',
  catalog_import: '/catalog-import',
  settings: '/settings',
  catalog_graph: '/catalog-graph',
  explore: '/explore',
  devtools: '/devtools',
  opencost: '/opencost',
  cicd: '/ci-cd',
  api: '/api',
  dependencies: '/dependencies',
  risc: '/risc',
  lighthouse: '/lighthouse',
  definition: '/definition',
  diagram: '/diagram',
};
