name: Lint and compile plugin

on:
  pull_request:

jobs:
  compile_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # From mise.toml
          cache: 'npm'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Prettier
        run: yarn run prettier:check

      - name: Run lint
        run: yarn run lint:all

      - name: Run tsc
        run: yarn run tsc
