name: Lint and compile plugin

on:
  pull_request:

jobs:
  compile_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - working-directory: plugins/ros
        run: corepack enable
      - working-directory: plugins/ros
        run: yarn install --immutable
      - working-directory: plugins/ros
        run: yarn prettier:check
      - working-directory: plugins/ros
        run: yarn lint
      - working-directory: plugins/ros
        run: yarn tsc
