name: Lint and compile plugin

on:
  pull_request:

jobs:
  compile_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn prettier:check
      - run: yarn lint
      # tsc outputs type definitions to dist-types/ in the repo root, which are then consumed by the build
      - run: yarn tsc
